apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.postgres.yml -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
    - name: "15900"
      port: 15900
      targetPort: 5900
  selector:
    io.kompose.service: selenium
